#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Not enough arguments"
    echo ""
    echo "Use: cegar promela_system property"
    exit 1
fi

PROG=$1
PROP=$2
BYMC_HOME=`dirname $0`

SPIN=spin
PAN_COMP_FLAGS="-DVECTORSZ=2048 -DCOLLAPSE -DSC"
PAN_FLAGS="-m100000" #-m50000000"
SPIN_OUT="spin.out"
cmd=""
step="0"
rand=""
out=""

CUR_DIR=`pwd`
cd $BYMC_HOME
./make.sh || (cd $CUR_DIR; exit 1)
cd $CUR_DIR

if [ "$CONTINUE" == "" ]; then
    CAMLRUNPARAM="b" $BYMC_HOME/run.native -a $PROG || exit 1
fi

rm -rf $SPIN_OUT spin.trace refinement.out

while [ "$cmd" != "q" ]; do
    $SPIN -a abs-counter.prm \
        && gcc $rand $PAN_COMP_FLAGS -o ./pan pan.c \
        && ./pan $PAN_FLAGS -N $PROP -a 2>&1 | tee $SPIN_OUT

    if egrep -q "errors: +0" $SPIN_OUT; then
        echo "The property is verified in $step refinement steps"
        out="|00:exitcode=ok|01:valid=yes|02:spurious=no"
        cmd="q"
    else
        ./pan -r | egrep '(^GS{|START OF CYCLE)' | tee spin.trace \
        && CAMLRUNPARAM="b" $BYMC_HOME/run.native -t spin.trace $PROG 2>&1 | tee refinement.out
        echo -e "The trace in the ABSTRACT system (produced by spin):\n"
        echo -n "     0  "; head -n 1 spin.trace # start with 0
        tail -n '+2' spin.trace | cat -n
        echo ""
        
        if grep "Sorry" refinement.out; then
            if [ "$AUTO" == "" ]; then
                echo "Enter to try another trace, q<Enter> to exit"
                rand="-DT_RAND"
                read cmd
            else
                cmd="q"
            fi
        elif grep "error" refinement.out \
                || grep "not spurious" refinement.out; then
            echo "It took $step refinement steps"
            out="|00:exitcode=ok|01:valid=no|02:spurious=no"
            cmd="q"
        else
            step=$((step+1))
            if [ "$DEBUG" != "" ]; then
                echo "Enter to continue, q<Enter> to exit"
                read cmd
            fi
        fi
    fi
done

if [ "$out" == "" ]; then
    out="|00:exitcode=quit|01:valid=maybe|02:spurious=maybe"
fi


spin_data=`$BYMC_HOME/parse-spin-out.py $SPIN_OUT`
common="|03:refinements=$step|04:sys=`basename $PROG .pml`|05:spec=`basename $PROP .never`"
echo "$out|$common|$spin_data" >>verdict.txt

