#!/bin/bash
#
# Check the result of PIA data abstraction with FAST.
#
# Igor Konnov, 2014

FAST=${FAST:-"fast"}
FAST_PLUGIN=${FAST_PLUGIN:-"lash-msdf"}
MEM_LIMIT="unlimited"
TIME_LIMIT="unlimited"

# parse options
TEMPOPTS=`POSIXLY_CORRECT=1 getopt -o h --long help,plugin:,limit-time:,limit-mem: -n '$@' -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

function help_and_exit() {
    echo "use $0 <switches> prog spec <bymc_switches>"
    echo " where <switches> are"
    echo "  --plugin <plugin>: set fast engine to <plugin> (default: lash-msdf)"
    echo "  --limit-time: limit (in seconds) cpu time of subprocesses (ulimit -t)"
    echo "  --limit-mem: limit (in MB) virtual memory of subprocesses (ulimit -v)"
    echo "  -h|--help: show this help message"
    exit 1
}

eval set -- "$TEMPOPTS"
while true ; do
    case "$1" in
    --limit-time) TIME_LIMIT=$2 ; shift 2 ;;
    --limit-mem) MEM_LIMIT=$((1024*$2)) ; shift 2 ;;
    --plugin) FAST_PLUGIN=$2 ; shift 2 ;;
    -h|--help) help_and_exit ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; help_and_exit ;;
    esac
done

echo ulimit -SHv $MEM_LIMIT
ulimit -SHv $MEM_LIMIT
echo ulimit -SHt $TIME_LIMIT
ulimit -SHt $TIME_LIMIT

PROG=$1
SPEC=$2
shift 2
export BYMC_FLAGS="$@ $BYMC_FLAGS"

# run the tool
export TARGET_MC=fast
export FAST_PLUGIN
`dirname $0`/script/refinement-loop.sh "$PROG" "$SPEC"

