#!/bin/bash
#
# Run the abstraction refinement loop with nusmv in bmc mode

DEPTH=10
NUSMV_VERBOSE=0
ONE_SHOT=0

# parse options
TEMPOPTS=`getopt -o d:w: --long depth:,nusmv-verbose:,one-shot -n '$@' -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMPOPTS"
while true ; do
    case "$1" in
    -d|--depth) DEPTH=$2 ; shift 2 ;;
    -w|--nusmv-verbose) NUSMV_VERBOSE=$2 ; shift 2 ;;
    --one-shot) ONE_SHOT=1 ; shift 1 ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
    esac
done

# run the tool
DEPTH=$DEPTH NUSMV_VERBOSE=$NUSMV_VERBOSE TARGET_MC=nusmv-bmc \
    `dirname $0`/cegar "$@"

