#!/bin/bash
#
# Run the abstraction refinement loop with nusmv in bdd mode

NUSMV_VERBOSE=0
MEM_LIMIT="unlimited"
TIME_LIMIT="unlimited"

# parse options
TEMPOPTS=`getopt -o w: --long nusmv-verbose:,limit-time:,limit-mem: -n '$@' -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMPOPTS"
while true ; do
    case "$1" in
    -w|--nusmv-verbose) NUSMV_VERBOSE=$2 ; shift 2 ;;
    --limit-time) TIME_LIMIT=$2 ; shift 2 ;;
    --limit-mem) MEM_LIMIT=$((1024*$2)) ; shift 2 ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
    esac
done

echo ulimit -SHv $MEM_LIMIT
ulimit -SHv $MEM_LIMIT
echo ulimit -SHt $TIME_LIMIT
ulimit -SHt $TIME_LIMIT

# run the tool
DEPTH=$DEPTH NUSMV_VERBOSE=$NUSMV_VERBOSE TARGET_MC=nusmv-bdd \
    `dirname $0`/cegar "$@"

