#!/bin/sh

if [ "$#" -lt 2 ]; then
    echo "Not enough arguments"
    echo ""
    echo "Use: cegar promela_system property"
    exit 1
fi

PROG=$1
PROP=$2

SPIN=spin
cmd=""

CAMLRUNPARAM="b" ./run.native -a $PROG

while [ "$cmd" != "q" ]; do
    $SPIN -a -N $PROP abs-counter.prm \
        && gcc -o ./pan pan.c && ./pan -a -m1000000 \
        && $SPIN -t -N $PROP abs-counter.prm | grep 'GS{' | tee spin.out

    if grep -q -v "errors: 1" spin.out; then
        CAMLRUNPARAM="b" ./run.native -t spin.out $PROG | tee refinement.out
        echo -n "     0  "; head -n 1 spin.out # start with 0
        tail -n '+2' spin.out | cat -n
        echo ""

        if grep "Sorry" refinement.out; then
            cmd="q"
        else
            echo "Enter to continue, q<Enter> to exit"
            read cmd
        fi
    else
        echo "The property is verified"
        cmd="q"
    fi
done
