#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Not enough arguments"
    echo ""
    echo "Use: cegar promela_system property"
    exit 1
fi

PROG=$1
PROP=$2

SPIN=spin601
cmd=""
step="0"
rand=""

if [ "$CONTINUE" == "" ]; then
    CAMLRUNPARAM="b" ./run.native -a $PROG || exit 1
fi

rm -rf spin.out spin.trace refinement.out

while [ "$cmd" != "q" ]; do
    $SPIN -a -N $PROP abs-counter.prm \
        && gcc $rand -o ./pan pan.c && ./pan -a -m100000 2>&1| tee spin.out

    if egrep -q "errors: +0" spin.out; then
        echo "The property is verified in $step refinement steps"
        cmd="q"
    else
        $SPIN -t -N $PROP abs-counter.prm | grep 'GS{' | tee spin.trace \
        && CAMLRUNPARAM="b" ./run.native -t spin.trace $PROG 2>&1 | tee refinement.out
        echo -n "     0  "; head -n 1 spin.trace # start with 0
        tail -n '+2' spin.trace | cat -n
        echo ""

        
        if grep "Sorry" refinement.out; then
            echo "Enter to try another trace, q<Enter> to exit"
            rand="-DT_RAND"
            read cmd
        elif grep "error" refinement.out \
                || grep "not spurious" refinement.out; then
            echo "It took $step refinement steps"
            cmd="q"
        else
            step=$((step+1))
            if [ "$INTERACT" != "" ]; then
                echo "Enter to continue, q<Enter> to exit"
                read cmd
            fi
        fi
    fi
done
